# Generated by Django 4.1.2 on 2022-11-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hurtos',
            fields=[
                ('ano', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Ncasos', models.PositiveIntegerField()),
                ('residencia', models.PositiveIntegerField()),
                ('personas', models.PositiveIntegerField()),
                ('comercio', models.PositiveIntegerField()),
                ('automotores', models.PositiveIntegerField()),
            ],
        ),
    ]
