# Generated by Django 4.1.2 on 2022-11-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuertesViolentas',
            fields=[
                ('ano', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('personas', models.PositiveIntegerField()),
                ('suicidios', models.PositiveIntegerField()),
                ('muertesAccidentes', models.PositiveIntegerField()),
                ('muerteTransporte', models.PositiveIntegerField()),
                ('homicidio', models.PositiveIntegerField()),
            ],
        ),
    ]
