# Generated by Django 4.1.2 on 2022-11-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolenciaIntrafamiliar',
            fields=[
                ('ano', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Ncasos', models.PositiveIntegerField()),
                ('AdultoMayor', models.PositiveIntegerField()),
                ('NiñoAdolecente', models.PositiveIntegerField()),
                ('OtrosFamiliares', models.PositiveIntegerField()),
                ('Pareja', models.PositiveIntegerField()),
            ],
        ),
    ]
